//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAPS.SJK.UI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LAPS.SJK.UI.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentang Kita.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Aplikasi.
        /// </summary>
        public static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontak.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanggal Dan Jam.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanggal Dan Jam.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label text.
        /// </summary>
        public static string Label_text {
            get {
                return ResourceManager.GetString("Label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahasa.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Utama.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uang.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harus minimal 5 karakter.
        /// </summary>
        public static string Must_be_at_least_5_charachters {
            get {
                return ResourceManager.GetString("Must_be_at_least_5_charachters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must contain only letters a-z, numbers and underscore _.
        /// </summary>
        public static string Must_contain_only_letters {
            get {
                return ResourceManager.GetString("Must_contain_only_letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit dan test pesan error .
        /// </summary>
        public static string Submit_and_test_error_messages {
            get {
                return ResourceManager.GetString("Submit_and_test_error_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field ini mandatori.
        /// </summary>
        public static string This_field_is_required {
            get {
                return ResourceManager.GetString("This_field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip help.
        /// </summary>
        public static string Tooltip_help {
            get {
                return ResourceManager.GetString("Tooltip_help", resourceCulture);
            }
        }
    }
}
